#FROM mcr.microsoft.com/windows/nanoserver:1809
#FROM mcr.microsoft.com/windows/nanoserver:1903
#FROM mcr.microsoft.com/windows/nanoserver:20H2
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

RUN ["cmd.exe", "/C", "echo The wind caught it. > gattaca.txt"]
CMD ["cmd.exe", "/S", "/C", "type", "gattaca.txt"]
